### ISSUE TITLE
建议采用CodeMirror编辑器,便于快捷键映射

### ISSUE THREAD

**Issue by dnknn** [atjason/iCode#2]
iCode 非常简约优秀, 但是可否支持Sublime按键映射或采用CodeMirror编辑器

Can support ⌨ Sublime keyboard mapping for CodeMirror-editor❓	👇

- ## https://codemirror.net/demo/sublime.html
- #### https://github.com/codemirror/CodeMirror

----
Why ?  because it's hotkey  is very versatile and powerful , It is the same shortcut key in many places,, 
E.g **🐵Tampermonkey** &emsp;or  [**Stylus**](https://github.com/openstyles/stylus/)&emsp;.etc
### **`Stylus`** 是一款 🅲🆂🆂 样式专用的浏览器扩展
https://chrome.google.com/webstore/detail/clngdbkpkpeebahjckkjfobafhncgmne

> `Tampermonkey `和 `Stylus` 都默认使用Sublime按键映射, 非常方便好用.

![Sublime](https://user-images.githubusercontent.com/10995302/87325219-bfe34c00-c563-11ea-9919-c2bc5afea4bf.gif)

☝The gif demo above is a Chrome-extension of `Stylus`

Most useful ⌨ | to
------------ | -------------
Ctrl+Shift+D | duplicate line
Ctrl+Shift+⇅ | exchange line
Ctrl+D |  Highlight matching & multi-point selection
Alt+F3 |  Match all highlights
Ctrl+J  |  Join line
Ctrl+Enter↵ |  insert Line After
Ctrl+Shift+Enter↵ |  insert Line before
F2/Ctrl+F2 |  bookmarks
.etc | .etc

---

![0713225616](https://user-images.githubusercontent.com/10995302/87319333-13519c00-c55c-11ea-8f19-501af8a4a067.png)

But the current default Ctrl+D is to delete line.

Stylus浏览器扩展的编辑器和Tampermonkey浏览器扩展的编辑器都默认用Sublime按键映射

They all use CodeMirror, and then the same optional keyboard mapping👇 Can refer to them👇
Their default options are also `Sublime` , Only `Sublime` has the most hotkeys.
![0714000222](https://user-images.githubusercontent.com/10995302/87326453-519f8900-c565-11ea-89f5-6d17927833ea.png)

![Stylus](https://user-images.githubusercontent.com/10995302/87326724-b4912000-c565-11ea-9750-f15de315ca72.gif)

**Comment by atjason** [comment]
很棒的建议，欢迎提交代码 😂

**Comment by dnknn** [comment]
> 很棒的建议，欢迎提交代码 😂

好像就是用CodeMirror编辑器, 只是没有使用高级按键映射而已对吧
